# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/block_design/block_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design || ORIG_REF_NAME==block_design} -quiet] -quiet

# IP: bd/block_design/ip/block_design_processing_system7_0_0/block_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_processing_system7_0_0 || ORIG_REF_NAME==block_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_gpio_0_0 || ORIG_REF_NAME==block_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_gpio_1_0/block_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_gpio_1_0 || ORIG_REF_NAME==block_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_bram_ctrl_0_0/block_design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==block_design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_timer_0_0/block_design_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_timer_0_0 || ORIG_REF_NAME==block_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_ps7_0_axi_periph_0/block_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==block_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_rst_ps7_0_50M_0/block_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==block_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_axi_bram_ctrl_0_bram_0/block_design_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==block_design_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_xbar_0/block_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_xbar_0 || ORIG_REF_NAME==block_design_xbar_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_2/block_design_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_pc_2 || ORIG_REF_NAME==block_design_auto_pc_2} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_1/block_design_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_pc_1 || ORIG_REF_NAME==block_design_auto_pc_1} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_0/block_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_pc_0 || ORIG_REF_NAME==block_design_auto_pc_0} -quiet] -quiet

# IP: bd/block_design/ip/block_design_auto_pc_3/block_design_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==block_design_auto_pc_3 || ORIG_REF_NAME==block_design_auto_pc_3} -quiet] -quiet

# XDC: bd/block_design/block_design_ooc.xdc
