# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0.xci
# IP: The module: 'block_design_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0.xci
# IP: The module: 'block_design_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/2adri/AES_Encryption/AES_Encryption.srcs/sources_1/bd/block_design/ip/block_design_axi_gpio_0_0/block_design_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_design_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
